### ISSUE TITLE
info on nodes

### ISSUE THREAD

**Issue by tinigarske** [dide-tools/didewin#6]
Is the information on which node a job is run on stored in the task bundle object? Would that be possible?

**Comment by richfitz** [comment]
I will look into this - I might need Wes to add a little extra bit to the output from the submission though.

**Comment by richfitz** [comment]
Looks like I need to get @weshinsley to add something to the output of the `submit_1.php` page to get that information directly at job submission.

In the meantime I'm wiring up some bits and pieces to let you query this.

**Comment by weshinsley** [comment]
If I understand the question correctly...

You can get the information easily enough by doing:

job view 1234567 /scheduler:fi--didemrchnb

and parse for something like

Allocated Nodes                 : FI--DIDEMRC13

HOWEVER - I can't "trivially" return that at submission, because the job 
is not yet running at that point in the HPC cycle; I think I'd have to 
speculative wait a second or so (assuming there are free resources and 
the queue is behaving itself ok), run the job view query separately from 
the submit and see if it's allocated anything yet.

W.

**Comment by richfitz** [comment]
Ah, of course :flushed:

I can get node information after the job is running already so it's all good.  I'll try and expose something that wraps that up in the R interface.

**Comment by richfitz** [comment]
There is node information printed in the log - is that enough?
